# Generated by Django 3.2 on 2022-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0002_blog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_string',
            field=models.CharField(max_length=10000),
        ),
    ]
