# Generated by Django 3.2 on 2022-12-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0003_alter_blog_html_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_modified',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
