# Generated by Django 3.2 on 2022-12-22 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApiBlog', '0004_auto_20221222_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_valid',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ReplyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_modified', models.SmallIntegerField(default=0)),
                ('is_valid', models.SmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='ApiBlog.blog')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Reply',
            },
        ),
    ]
