# Generated by Django 3.2 on 2022-12-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0005_auto_20221222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyblog',
            name='target_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='ApiBlog.blog'),
        ),
    ]
