# Generated by Django 3.2 on 2022-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0006_alter_replyblog_target_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyblog',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
