# Generated by Django 3.2 on 2023-03-16 15:40

from django.db import migrations, models
import module.ApiBlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0008_alter_replyblog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thubnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=module.ApiBlog.models.blog_dir_path),
        ),
    ]
