# Generated by Django 3.2 on 2023-03-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0009_blog_thubnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thubnail_image',
            new_name='thumbnail_image',
        ),
    ]
