# Generated by Django 3.2 on 2023-03-31 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0010_rename_thubnail_image_blog_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, null=True)),
                ('description', models.CharField(default='', max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiBlog.blogseries'),
        ),
    ]
