# Generated by Django 3.2 on 2023-04-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0012_blogseries_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
    ]
