# Generated by Django 3.2 on 2023-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0013_remove_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_string',
            field=models.CharField(max_length=20000),
        ),
    ]
