# Generated by Django 3.2 on 2023-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0014_alter_blog_html_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
