# Generated by Django 3.2 on 2023-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0015_blog_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status_type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
