# Generated by Django 3.2 on 2023-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0017_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status_type',
            field=models.SmallIntegerField(default=2),
        ),
    ]
