# Generated by Django 3.2 on 2023-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0018_alter_blog_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='domain',
            field=models.SmallIntegerField(default=1),
        ),
    ]
