# Generated by Django 3.2 on 2023-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0019_blog_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogseries',
            name='domain',
            field=models.SmallIntegerField(default=1),
        ),
    ]
