# Generated by Django 3.2 on 2023-06-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0020_blogseries_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogseries',
            options={'verbose_name': 'BlogSeries', 'verbose_name_plural': 'BlogSeries'},
        ),
    ]
