# Generated by Django 3.2 on 2023-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0021_alter_blogseries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_cn',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_es',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ja',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_string_cn',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_string_es',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_string_ja',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_cn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_es',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_ja',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title_cn',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title_es',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title_ja',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
