# Generated by Django 3.2 on 2023-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0022_auto_20230617_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_string',
            field=models.CharField(max_length=100000),
        ),
    ]
