# Generated by Django 3.2 on 2024-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiBlog', '0024_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='is_valid',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='last_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
