# Generated by Django 3.2 on 2024-01-07 08:01

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_auto_20230102_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=core.user.models.avatar_dir_path),
        ),
    ]
